### ISSUE TITLE
Clustering using Jaccard program from lab 4

### ISSUE THREAD

**Issue by soujanyaduvvi** [curtisullerich/419#1]
I have been trying to execute this program but getting String Index Out of Bounds Exception.
You took an input file named 123454.
Can you please provide the input file sir. Or please let me know the format of the input taken.

**Comment by curtisullerich** [comment]
Hi Soujanya, Map_One is expecting files with lines of the form $DOC_ID-$DOC_TEXT where $DOC_TEXT has no newlines or punctuation. See the lab guide for more details: https://github.com/curtisullerich/419/blob/master/lab4/Lab4.pdf

Example:
2387419238-Lorem ipsum dolor sit amet consectetur adipiscing elit
128378172387-Has anyone really been far as decided to use even go want to do look more like

**Comment by soujanyaduvvi** [comment]
Thank you sir for your response, this is the input I have taken 

32301-MapReduce Simplified Data Processing on Large Clusters Jeffrey Dean and Sanjay Ghemawat jeffgooglecom sanjaygooglecom Google Inc
32305-Abstract MapReduce is a programming model and an associated implementation for processing and generating large data sets Users specify a map
3231-function that processes a keyvalue pair to generate a set of intermediate keyvalue pairs and a reduce function that merges all intermediate
3301-values associated with the same intermediate key Many real world tasks are expressible in this model as shown in the paper
323015-Programs written in this functional style are automatically parallelized and executed on a large cluster of commodity machines The runtime
42301-system takes care of the details of partitioning the input data scheduling the programs execution across a set of machines handling machine
32501-failures and managing the required intermachine communication This allows programmers without any experience with parallel and distributed

But still the same error persisted.
![screenshot from 2015-08-16 10 41 28](https://cloud.githubusercontent.com/assets/11198011/9292102/68d563da-4403-11e5-8e0a-1b57bb810688.png)
Hereby i am attaching the image of the error.

**Comment by soujanyaduvvi** [comment]
After excluding the whitespaces I got the required output sir
Thank you.

**Comment by curtisullerich** [comment]
Ah, sorry, I must have misread the format definition. Glad you got it working.
